### ISSUE TITLE
Outcome enlistment handle leak in `OletxTransactionManager`

### ISSUE THREAD

**Issue by swh-cb** [softwarehelden-com/Softwarehelden.Transactions.Oletx#22]
After the transaction has been completed or aborted, the outcome enlistment handle in `OletxTransactionManager` must be released again.

**Comment by caviyacht** [comment]
@swh-cb , Is this project still active? We are currently upgrading to .NET 6 and I would like to utilize this library, but was concerned with a potential leak. Is this leak a huge issue, or just something that needs to be cleaned up?

**Comment by swh-cb** [comment]
The issue must be fixed but does not affect productive use of the library.

We still use the library in our products targeting .NET 6 without problems. Once .NET 8 is released with long term support (LTS), we will probably switch back to `System.Transactions`. .NET 7 added distributed transaction support for Windows only (https://github.com/dotnet/runtime/pull/72051). However, you need the latest version of `Microsoft.Data.SqlClient` to avoid deadlocks with MSSQL (https://github.com/dotnet/SqlClient/pull/1801). If an Oracle database is to participate in the transaction, the `OletxCompatibilityLoadContext` is still required in combination with the unmanaged ODP.NET driver `Oracle.DataAccess`. There is an open feature request for distributed transaction support in ODP.NET Core on .NET 7 and Windows (https://github.com/oracle/dotnet-db-samples/issues/267).

**Comment by caviyacht** [comment]
@swh-cb , Thanks for responding so quickly. Ok, so sounds like we should be good to use this (I believe). We will be on .NET 6 for the foreseeable future (tied to a 3rd party framework).

We are using the latest version of `System.Data.SqlClient` (v4.8.5). I was wondering, the Sql patch logic that you recommend (` MsSqlPatcher.Patch(typeof(SqlConnection).Assembly);`), is that still needed for this version as well? I'm going to assume yes.

**Comment by swh-cb** [comment]
@caviyacht Exactly, `System.Data.SqlClient` needs to be patched, even for the latest version `4.8.5`. The fix from https://github.com/dotnet/SqlClient/pull/1624 for `Microsoft.Data.SqlClient` was not backported. We are currently using the (patched) version `4.1.0` of `Microsoft.Data.SqlClient` in our environments.

**Comment by swh-cb** [comment]
This issue won't be fixed because distributed transactions are supported on Windows starting with .NET 7.0.
